spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Отключаем автоматическое управление схемой Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true  # Явно включаем Liquibase
    change-log: classpath:db/changelog/db.changelog-master.yaml