spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ZzplyY
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Отключаем автоматическое управление схемой Hibernate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true  # Явно включаем Liquibase
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081  # Новый порт
