spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Чтобы Hibernate обновил схему
    show-sql: true  # Чтобы видеть SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true
